name: Test slowdown

on:
  workflow_dispatch:
  push:
    branches: [ "feature/testSlowdown" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         goals: ["clean install -Pfastest -T4C", "clean verify -T4C"]
         cache: ["-Ddevelocity.cache.local.enabled=false", "-Ddevelocity.cache.local.enabled=true"]
         develocity: [true, false]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Conditionally remove Develocity and CCUD extensions
        if: matrix.develocity == false
        run: rm .mvn/extensions.xml

      - name: Build with Maven
        id: build
        run: ./repeat.sh "mvn ${{ matrix.goals }} ${{ matrix.cache }} -Ddevelocity.url=https://ge.solutions-team.gradle.com/"
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_API_TOKEN }}

      - name: Set summary
        run: |
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "Develocity: ${{ matrix.develocity }}" >> $GITHUB_STEP_SUMMARY
          echo "Goals: ${{ matrix.goals }}" >> $GITHUB_STEP_SUMMARY
          echo "Cache: ${{ matrix.cache }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build.outputs.times }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build.outputs.average }}" >> $GITHUB_STEP_SUMMARY

